---
title: 'ISS 2102: Coursework Marks'
output:
  pdf_document: default
  html_document:
    includes:
      after_body:
      - include_footer.html
      before_body:
      - include_header.html
      
  
---


**Academic Regulations.**

A student, who fails to attend 80% of the classes as prescribed in a course automatically disqualifies herself/himself from sitting examinations in that course.

If a student is unable to attend classes for health reasons for longer than 72 hours, he/she must notify the appropriate department of the facts as soon as possible and submit certification in support thereof by a medical practitioner registered in accordance with the Medical, Dental and Allied Health Professions Act and any other relevant Acts.

For absence on grounds other than health, prior permission from the Dean on the recommendation of the Chairperson of Department concerned is needed.


**CW is the average of the best 3 assessments. **

**The class representative can collect the marked scripts from office W16.**


```{r echo=FALSE}
library(readxl)
cw21022021<- read_excel("cw21022021.xlsx")
library(DT)
datatable(cw21022021, rownames = FALSE,  options = list(pageLength = 100, scrollX=T,columnDefs=list(list(targets=2,visible=TRUE),list(className = 'dt-center', targets = 1:4))) )%>%
  formatStyle(
    'Quiz_1',
    color = styleInterval(c(0.495, 0.75), c('red', 'black', 'green')), fontWeight = 'bold') %>%
  formatPercentage('Quiz_1', 0)%>%
formatStyle(
    'Test_1',
    color = styleInterval(c(0.495, 0.745), c('red', 'black', 'green')), fontWeight = 'bold') %>%
  formatPercentage('Test_1', 0)%>%
  formatStyle(
    'Test_2',
    color = styleInterval(c(0.495, 0.745), c('red', 'black', 'green')), fontWeight = 'bold') %>%
  formatPercentage('Test_2', 0)%>%
    formatStyle(
    'Test_3',
    color = styleInterval(c(0.495, 0.75), c('red', 'black', 'green')), fontWeight = 'bold') %>%
  formatPercentage('Test_3', 0)%>%
  formatStyle(
    'CW',
    color = styleInterval(c(0.49, 0.75), c('red', 'black', 'green')), fontWeight = 'bold') %>%
  formatPercentage('CW', 0)
  

```

