---
title: "HIT 121: Engineering Mathematics II"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [include_header.html, include_lessons_nav.html]
      after_body: [include_lessons_nav_end.html, include_footer.html]
---

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

Lecturer: **K Mutangi**

Office  : W16

Email   : kmutangi@gmail.com

Phone   : +263242 741428-30 Ext 2372

</div>



Assessment shall comprise of 3 in class tests and an end of semester examination. The end of semester examination counts 75%, and the continuous assessment counts 25% towards the final mark. Only those who score an average of 50% in the 3 tests will be allowed to write the end of semester 
examination. All tests and the exam are mandatory. Discuss any potential conflicts well before the test/exam date.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

<center>
**Online Learning **
</center>
While physical congregation  for classes has been suspended, online learning will continue so as to minimise disruptions to the semester.

<center>
**Online Quizzes **
</center>

(@) Links to online quizzes will be posted on the respective course's webpage.
(@) Quiz dates will be posted on the notices below.
(@) The quizzes are  compulsory and will contribute to the final coursework mark.
(@) Instructions:
    * When entering your surname  the first letter must be an uppercase letter, the rest must be lowercase letters. Example: **Surname**
    * When entering the letters on your registration number, please use uppercase letters only. Example: **H000000A**
    * Only click the submit button when you have verified your answers. The submit button will be on the last page of the quiz. If a student makes  multiple submissions, only the first one will be recorded.
(@) To acquaint yourself with the quiz format click the link [Sample Quiz(Linear Aldebra, ODEs, Vector Calculus, Laplace Transforms)](https://docs.google.com/forms/d/e/1FAIpQLSdNFcWuuoTi5Oh99tnF7uLuP4qwgl_Xju6xvoCc1w7V9WDH6w/viewform?usp=sf_link).  
Tutorials will have the same format as quizzes. The only difference will be that they will give detailed solutions after submission.
</div>



### Course Content
(@) Linear Algebera
(@) Ordinary Differential Equations
(@) Vector Calculus
(@) Laplace Transforms

[Course Outline (pdf)](https://drive.google.com/file/d/1YTM2qJU8BMlOpyXgHQxKCzXpT6_iHT0F/view?usp=sharing)

### Lecture Notes

[Linear Algebra I](https://drive.google.com/file/d/1djpop6x1BY1wN7lPyhQRthUcFcjGxJwL/view?usp=sharing)

[Linear Algebra II](https://drive.google.com/file/d/1wtGffPnOoLBvV5tZgAkNUJ6pw5QxxdAs/view?usp=sharing)

[Laplace Transforms](https://drive.google.com/file/d/1feoB6yBJ9zSPkRDRn_ec2XDMwue1LDcC/view?usp=sharing)

[Ordinary Differential Equations I](https://drive.google.com/file/d/1YT8uUMDoNXOC0_B0VOKAGCAntD8KKCUo/view?usp=sharing)

[Ordinary Differential Equations II](https://drive.google.com/file/d/1ZgyyM8xoNpQIhZgidEiHnwgkkaXGxEUs/view?usp=sharing)

[Ordinary Differential Equations III](https://drive.google.com/file/d/1epZNoi3RZFoSmJxAZ9ZteXXCoVncA8ME/view?usp=sharing)

[Vector Calculus I](https://drive.google.com/file/d/1DaNG9UAFp86MZFsuX0J9iT9wqPr_nXUi/view?usp=sharing)

[Vector Calculus II](https://drive.google.com/file/d/15UUpb82LWWbLsRkXt05V_j-ge30rXCYW/view?usp=sharing)


### Books

[Advanced Engineering Mathematics](https://drive.google.com/file/d/1Y-37NYSAWCiSOnlMNiFPV8aQOjJx_eWu/view?usp=sharing)

### Worksheets


#### **2020**

#### **2019**

#### **2018**

[Worksheet  (2018)](https://drive.google.com/open?id=1oLNr8FYGHDIXHHfsGQBJLDx35hla-aVJ)





### Tests

#### **2019**

[Supplementary Test (2019)](https://drive.google.com/file/d/1n5QvKQ_YdXv6vsyZGn3-zBP3ereTqAwe/view?usp=sharing)

#### **2018**

[Linear Algebra Test (2018)](https://drive.google.com/file/d/1FOcgTUQv08dgWXtC3Zoq6R3__7fHsYYs/view?usp=sharing)

[ODEs Test 1 (2018)](https://drive.google.com/open?id=1uAwM8HfCnV6Uvo6vlF4vYz7Lse-MVa-c)

[Vector Calculus Test (2018)](https://drive.google.com/open?id=1rYNJ4RqZ_itoWrO290HCZBan6uKJU6w2)


### Past Examinations





***
### [HIT 122: Mathematics For Technologists II](hit122.html){.continue-link}
### [ISS 126: Number Theory](iss126.html){.continue-link}
### [ICS 226/ISE 225: Numerical Analysis](ics225.html){.continue-link}
