---
title: "HIT 122: Mathematics For Technologists II"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [include_header.html, include_lessons_nav.html]
      after_body: [include_lessons_nav_end.html, include_footer.html]
---
## **Course information** {.tabset .tabset-fade}
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
Lecturer: **T. Mutusva**

Office  : W16

Email   : tmutusva@hit.ac.zw

Phone   : +263242 741428-30 Ext 2372

Website : https://tnmutusva.github.io/course
</div>


Assessment shall comprise of 4 in class tests, one assignment and an end of semester examination. The end of semester examination counts 75%, and the continuous assessment counts 25% towards the final mark. Only those who score an average of 50% in the 4 tests will be allowed to write the end of semester 
examination. All tests and the exam are mandatory. Discuss any potential conflicts well before the test/exam date.



### Course Content
(@) Linear Algebera
(@) Ordinary Differential Equations
(@) Vector Calculus
(@) Laplace Transforms

For the detailed Course Outline click the link below:

[Course Outline](https://drive.google.com/open?id=1n_ke-u-6ycHlVj-Rmmlev3IhWfQcGbg8)

***
### Lecture Notes

[ Linear Algebra ](https://spark.adobe.com/page/LQZ536TE2sFA9/)




***
### Worksheets



#### **2020**

[Worksheet 1(2020)](https://drive.google.com/open?id=13pMST2W6B8Ytjfa8lRZQnlEUL2usWvQ3)



#### **2019**

[Worksheet 1 (2019)](https://drive.google.com/file/d/1QqQITzFhzlM4vkRXTLAVYAdOmQDvzbQB/view?usp=sharing),
[Worksheet 2 (2019)](https://drive.google.com/open?id=12rwyzSwLbLq3S93RXslBDMypVWC5bdkw),
[Worksheet 3 (2019)](https://drive.google.com/open?id=1YuUfzEW_uXZAvT6iYt6SMN0-Kwz60GuJ),
[Worksheet 4 (2019)](https://drive.google.com/open?id=1FDQKATnF181PFbl25VIiZMDLAfECIqAn)


***
### Tests

#### **2020**
[Test 1(2020)](https://drive.google.com/open?id=1IM6ALrjos4PP0Lz9VWe2wqO6fQ-Davvw)

#### **2019**
[Test 1 (2019)](https://drive.google.com/open?id=1uLLuLDuV09GWLf1eFqzjjjFKkA72_9kK),
[Test 2 (2019)](https://drive.google.com/open?id=1_bjGbG5N-Rzngg_dOQlKYbto8HgXd0S5),
[Test 2 (2019) Model Answers](https://drive.google.com/open?id=1-U3Pcgm4TlU_6PLmX1GUDPsY-Kkzk5H-)


***
### Past Examinations



[Examination (2018)](https://drive.google.com/open?id=1s15c_IJ54QyOlM_Sak4a23tvsxnOD3Vj),
[Examination (2019)](https://drive.google.com/open?id=1EsQMps01up61VamIX8V6cb12-skYwb_X)


### Coursework Marks



***

