---
title: "RStudio"
output:
  html_document:
    toc_float: true
    includes:
      before_body: [include_header.html]
      after_body: [ include_footer.html]
---
## **The R environment** {.tabset .tabset-fade .tabset-pills}
### R 


R is an integrated suite of software facilities for data manipulation, calculation and graphical display. It includes

+ an effective data handling and storage facility,
+ a suite of operators for calculations on arrays, in particular matrices,
+ a large, coherent, integrated collection of intermediate tools for data analysis,
+ graphical facilities for data analysis and display either on-screen or on hardcopy, and
+ a well-developed, simple and effective programming language which includes conditionals, loops, user-defined recursive functions and input and output facilities.

The term “environment” is intended to characterize it as a fully planned and coherent system, rather than an incremental accretion of very specific and inflexible tools, as is frequently the case with other data analysis software.

R, like S, is designed around a true computer language, and it allows users to add additional functionality by defining new functions. Much of the system is itself written in the R dialect of S, which makes it easy for users to follow the algorithmic choices made. For computationally-intensive tasks, C, C++ and Fortran code can be linked and called at run time. Advanced users can write C code to manipulate R objects directly.

[Click Here to download R](https://cran.r-project.org/mirrors.html)

***
 
 
 

### Rstudio

RStudio is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.

RStudio is available in **open source** and **commercial** editions and runs on the desktop (Windows, Mac, and Linux) or in a browser connected to RStudio Server or RStudio Server Pro (Debian/Ubuntu, Red Hat/CentOS, and SUSE Linux).

[Click here to download RStudio](https://rstudio.com/products/rstudio/)

 
***


### Number Theory

#### HTML files
(@) [Number Theory](rs2.html)

#### YouTube Videos

1. [Relations](https://youtu.be/OcsImJ36r_E)
2. [Sets](https://youtu.be/5kkMNfGK6So)

### Linear Algebra

[ Linear Algebra](rs1.html) 

### Statistics

1. [One Sample t-test](https://youtu.be/e15hPTO5aYs) 
2. [Descriptive Statistics](https://youtu.be/2jkzMwT0ZH0)

### Operations Reseaarch

#### HTML files

1. [Linear Programming](lpp.html)

 
 